Last login: Sun May 11 17:30:40 on ttys000 firebase init hosting:github
(base) christianmillar@Christians-MacBook-Air ~ % firebase init hosting:github

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /Users/christianmillar

Before we get started, keep in mind:

  * You are initializing your home directory as a Firebase project directory

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

✔ Please select an option: Use an existing project
✔ Select a default Firebase project for this directory: cryptic-cinema (Cryptic
Cinema)
i  Using project cryptic-cinema (Cryptic Cinema)

=== Hosting:github Setup

Error: Didn't find a Hosting config in firebase.json. Run firebase init hosting instead.
(base) christianmillar@Christians-MacBook-Air ~ % firebase init hosting

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /Users/christianmillar

Before we get started, keep in mind:

  * You are initializing your home directory as a Firebase project directory

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

✔ Please select an option: Use an existing project
✔ Select a default Firebase project for this directory: cryptic-cinema (Cryptic
Cinema)
i  Using project cryptic-cinema (Cryptic Cinema)

=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to be uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

✔ What do you want to use as your public directory? public
✔ Configure as a single-page app (rewrite all urls to /index.html)? Yes
✔ Set up automatic builds and deploys with GitHub? Yes
✔  Wrote public/index.html

i  Didn't detect a .git folder. Assuming /Users/christianmillar is the project root.
i  Authorizing with GitHub to upload your service account to a GitHub repository's secrets store.

Visit this URL on this device to log in:
https://github.com/login/oauth/authorize?client_id=89cf50f02ac6aaed3484&state=86823574&redirect_uri=http%3A%2F%2Flocalhost%3A9005&scope=read%3Auser%20repo%20public_repo

Waiting for authentication...

✔  Success! Logged into GitHub as christianmillar31

✔ For which GitHub repository would you like to set up a GitHub workflow?
(format: user/repository) christianmillar31/CrypticCinema

Error: Request to https://api.github.com/repos/undefined had HTTP Error: 404, Not Found

Having trouble? Try firebase [command] --help
(base) christianmillar@Christians-MacBook-Air ~ % cd ~/cryptic-cinema

(base) christianmillar@Christians-MacBook-Air cryptic-cinema % ls
public
(base) christianmillar@Christians-MacBook-Air cryptic-cinema % cd ~
rm firebase.json .firebaserc

rm: firebase.json: No such file or directory
rm: .firebaserc: No such file or directory
(base) christianmillar@Christians-MacBook-Air ~ % cd ~/cryptic-cinema
firebase init hosting

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /Users/christianmillar/cryptic-cinema

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

✔ Please select an option: Use an existing project
✔ Select a default Firebase project for this directory: cryptic-cinema (Cryptic
Cinema)
i  Using project cryptic-cinema (Cryptic Cinema)

=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to be uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

✔ What do you want to use as your public directory? public
✔ Configure as a single-page app (rewrite all urls to /index.html)? Yes
✔ Set up automatic builds and deploys with GitHub? No
✔  Wrote public/index.html

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...
i  Writing gitignore file to .gitignore...

✔  Firebase initialization complete!
(base) christianmillar@Christians-MacBook-Air cryptic-cinema % cd ~/Downloads
unzip cryptic-cinema.zip
mv cryptic-cinema ~/cryptic-cinema
cd ~/cryptic-cinema

unzip:  cannot find or open cryptic-cinema.zip, cryptic-cinema.zip.zip or cryptic-cinema.zip.ZIP.
mv: rename cryptic-cinema to /Users/christianmillar/cryptic-cinema/cryptic-cinema: No such file or directory
(base) christianmillar@Christians-MacBook-Air cryptic-cinema % git add .
git commit -m "Add project files"
git push origin main
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
(base) christianmillar@Christians-MacBook-Air cryptic-cinema % git init
git add .
git commit -m "first commit"
git remote add origin https://github.com/christianmillar31/CrypticCinema.git
git push -u origin main
Initialized empty Git repository in /Users/christianmillar/cryptic-cinema/.git/
[main (root-commit) 9a5531a] first commit
 4 files changed, 179 insertions(+)
 create mode 100644 .firebaserc
 create mode 100644 .gitignore
 create mode 100644 firebase.json
 create mode 100644 public/index.html
To https://github.com/christianmillar31/CrypticCinema.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/christianmillar31/CrypticCinema.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(base) christianmillar@Christians-MacBook-Air cryptic-cinema % git pull origin main --allow-unrelated-histories
git push origin main
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 862 bytes | 431.00 KiB/s, done.
From https://github.com/christianmillar31/CrypticCinema
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
To https://github.com/christianmillar31/CrypticCinema.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/christianmillar31/CrypticCinema.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(base) christianmillar@Christians-MacBook-Air cryptic-cinema %